version: '3.8'

services:
  frontend:
    image: gnsnghm/cloud-management-system
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: gnsnghm/cloud-management-backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
